### ISSUE TITLE
FIR and IIR filtering in brian2hears

### ISSUE THREAD

**Issue by victorbenichoux** [brian-team/brian2hears#1]
Hi guys,

I have recently experimented on implementing filtering with brian2 objects. The idea is that all the code here is codegen compatible, which could lead to performance. For now this is not really efficient.

For maximal "wow" factor, you can run the simple_anf.py example in the examples folder
## FIR Filtering

The first path I chose was to implement FIR filtering, by using a kind of shift-register structure. Thanks to a lot of help from @mstimberg, I managed to make this happen. The code is in `core.linearfilterbank.FIRFIlterbankGroup`, and `core.linearfilterbank.ShiftRegisterGroup`. 

The shift register is based on using a reference to the group's variable with rolled indices, and works like a charm. Applying the FIR filter coeficients is then implemented by adding a Synapses object with custom code to do the multiplication, and then a summed variable.

This may be used right now for HRTF filtering, albeit because this relies on a crude implementation of FIR filtering (no fft...) it won't be the most efficient in the long run.
## IIR Filtering

My second idea was to implement IIR filtering using the same method as in brian.hears (and scipy). This is achieved in `core.linearfilterbank.LinearFilterbankGroup`. 
To implement this, for each channel an array of intermediate value has to be held. To do so, I chose to explicitly construct code with variable names emulating arrays (i.e. x_0, x_1, ...). This is certainly not very efficient, but in general the number of taps in IIR filters (and in turn, the number of intermediate variables) is quite low (3 for the gammatone), so the difference may not be so big.
The code in those code objects is sensitive to issues such as brian-team/brian2#260 in brian2 (copy numpy array stuff).
The number of neurons is then the number of channels in the filterbank.
## Gammatone filtering

I was really happy that I could get to this point. I copied over some code from brian.hears which allowed me to implement the library.gammatone.GammatoneFilterbank object over my LinearFilterbankGroup.
Samplerate is set to 1./defaultclock.dt, but I haven't taken special care in clock stuff.
## TODO

There are no specific sound objects, or no fancy filterbank chaining and repeating options yet. This is actually very easy to implement, filter chaining is almost like reference variables and repeating/tiling may be implemented with indexed variables. I think the next step is to port as much of this brian hears infrastructure. I should also write documentation!

Tell me what you think!

**Comment by thesamovar** [comment]
Closing old issues since it looks like we're no longer pursuing this approach to brian2hears.

**Comment by victorbenichoux** [comment]
😿

**Comment by thesamovar** [comment]
Well if you have time to work on it I'm still open to it! :)
