### ISSUE TITLE
Found a bug when using Gammatone() 

### ISSUE THREAD

**Issue by odedbarz** [brian-team/brian2hears#10]
Hi, I tried to run the example in brian2hears intro (https://brian2hears.readthedocs.io/en/stable/introduction.html), but the code crashed when I tried to create the Gammatone filterbank,

In [8]: fb = Gammatone(sound, cf)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-e0715c0c5107> in <module>
----> 1 fb = Gammatone(sound, cf)

~/miniconda3/envs/brian2/lib/python3.8/site-packages/brian2hears/filtering/filterbanklibrary.py in __init__(self, source, cf, b, erb_order, ear_Q, min_bw, cascade)
    126                          np.array([A0*np.ones(len(cf)), A14, np.zeros(len(cf))]).T))
    127
--> 128         LinearFilterbank.__init__(self, source, self.filt_b, self.filt_a)
    129         if cascade is not None:
    130             self.decascade(cascade)

~/miniconda3/envs/brian2/lib/python3.8/site-packages/brian2hears/filtering/linearfilterbank.py in __init__(self, source, b, a)
    310         # Check not only for the availability of weave/Cython, but also whether
    311         # they can successfully compile a simple test program
--> 312         from brian2.codegen.runtime.weave_rt.weave_rt import WeaveCodeObject
    313         from brian2.codegen.runtime.cython_rt.cython_rt import CythonCodeObject
    314         if weave is not None and WeaveCodeObject.is_available():

ModuleNotFoundError: No module named 'brian2.codegen.runtime.weave_rt'

I checked on my computer and in the GitHub repository of the brian2 project. There is no such 'brian2.codegen.runtime.weave_rt' module.

Currently, as a fast fix, I just removed the reference to that module:

       # Check not only for the availability of weave/Cython, but also whether
        # they can successfully compile a simple test program
        #from brian2.codegen.runtime.weave_rt.weave_rt import WeaveCodeObject
        from brian2.codegen.runtime.cython_rt.cython_rt import CythonCodeObject
        if weave is not None: #and WeaveCodeObject.is_available():

And it seems to be working, at least for now.

**Comment by thesamovar** [comment]
Thanks for this! I can confirm this happens to me too and it's because when brian2 moved to Python 3 only we removed weave support (because it doesn't exist in Python 3). We didn't update brian2hears to work with this new version. Will fix in a couple of weeks time unless @mstimberg has a moment to do it before then.

**Comment by odedbarz** [comment]
Great! thank you!
