### ISSUE TITLE
Porting brian.hears library items

### ISSUE THREAD

**Issue by victorbenichoux** [brian-team/brian2hears#3]
For now, the LinearFilterbankGroup is almost syntactically equivalent to its homonym in brian.hears. It should therefore be quite straightforward to implement the "simple" library items of brian.hears (basically, copy/paste + take care of brian2 specific keyword arguments).

The only missing functionality is that it does not automatically chain filterbanks when a (or b) is 3D (as in brian.hears).

For more complex models, we need to implement control pathways.  I have not tried to do this yet.

**Comment by thesamovar** [comment]
Closing old issues since it looks like we're no longer pursuing this approach to brian2hears.
