### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by victorbenichoux** [brian-team/brian2hears#4]
For now the sound representation in brian2hears is just TimedArray. We may need to go beyond that, for example we need to have binaural sounds etc.

Do you think that we should take the same route as brian.hears (implement some subclass of np.ndarray), I have the feeling that this may mess up with the code generation...

Another point is that we could need the Sound to act as a kind of 2D-TimedArray when used in a neurongroup. Maybe it is best to derive from such a 3Dtimedarray class...

What do you think?

**Comment by thesamovar** [comment]
Closing old issues since it looks like we're no longer pursuing this approach to brian2hears.
