### ISSUE TITLE
Buffering and improved FIR filtering

### ISSUE THREAD

**Issue by victorbenichoux** [brian-team/brian2hears#5]
The FIR filtering is now based on a shift-register group + Synapses. This is highly unefficient, especially in python. 
In python, the best way to do FIR filtering is by computing the fft of the impulse response, and the sound, multiplying and ifft-ing.
I also suspect that going in this direction is going to be faster in CPP.

We would then have to provide the python and CPP implementations (we may need to implement FFT for CPP) of the FIR filtering. This part is not the hardest.

The main hurdle for this stratedy is that we need to hold some buffer for each channel in the filterbankgroup. This I believe does not yet exist in brian2 (or, does it?).

**Comment by thesamovar** [comment]
Closing old issues since it looks like we're no longer pursuing this approach to brian2hears.
